#!/bin/sh
set -eu

PREVIEW_PUBLIC_DIRECTORY="/site"
PREVIEW_LIST_FILE="$(mktemp /tmp/fcaj-link-previews.XXXXXX)"
trap 'rm -f "$PREVIEW_LIST_FILE"' EXIT HUP INT TERM

find "$PREVIEW_PUBLIC_DIRECTORY" -type f -name 'link-preview.svg' -print > "$PREVIEW_LIST_FILE"

if [ ! -s "$PREVIEW_LIST_FILE" ]; then
  echo "No link-preview.svg files were generated by Hugo." >&2
  exit 1
fi

PREVIEW_COUNT=0
while IFS= read -r PREVIEW_SVG; do
  PREVIEW_PNG="${PREVIEW_SVG%.svg}.png"
  rsvg-convert \
    --width=1200 \
    --height=630 \
    --output="$PREVIEW_PNG" \
    "$PREVIEW_SVG"
  PREVIEW_COUNT=$((PREVIEW_COUNT + 1))
done < "$PREVIEW_LIST_FILE"

echo "Rendered $PREVIEW_COUNT link preview PNG(s)."
